name: Build and Push Docker Images

on:
  push:
    branches: [main]
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get tag name
        id: get_tag
        run: |
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push CLI image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.cli
          push: true
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386
          tags: |
            tonykip/crewai:cli
            tonykip/crewai:${{ env.TAG }}
        if: startsWith(github.ref, 'refs/tags/')

      - name: Build and push project image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386
          tags: |
            tonykip/crewai:latest
            tonykip/crewai:${{ env.TAG }}
        if: startsWith(github.ref, 'refs/tags/')

      - name: Build and push CLI image (main branch)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.cli
          push: true
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386
          tags: tonykip/crewai:cli
        if: github.ref == 'refs/heads/main'

      - name: Build and push project image (main branch)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386
          tags: tonykip/crewai:latest
        if: github.ref == 'refs/heads/main'
